# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_hash1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pw_confirm',
        ),
    ]
