# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_user_pw_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hash1',
        ),
    ]
