# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20170920_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
